theme: jekyll-theme-merlot
show_downloads: "true"
github:
  zip_url: https://github.com/RintarouTW/LaTeX4TwitchChat/zipball/release
  tar_url: https://github.com/RintarouTW/LaTeX4TwitchChat/tarball/release
